services:
  db:
    container_name: postgresSQL
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
#    networks:
#      - pg-network

  web:
    container_name: webServer
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
      - db

  php:
    container_name: php
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  pgadmin:
    container_name: pgAdmin
    build:
      context: .
      dockerfile: docker/pgadmin/Dockerfile
    env_file:
      - .env
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
#    networks:
#      - pg-network

#networks:
#  pg-network:
